name: Snyk Security

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'     ## 2am daily

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Setup .NET
        uses: actions/setup-dotnet@3
        
      - name: Restore dependencies
        run: dotnet restore ./path/to/your.sln
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
